feat: support 1s candles
Nouzan/exc pull request #55
Opened 2023-04-27 06:32 UTC by rise0chen

Notice: test will failed, because of https://github.com/Nouzan/indicator/pull/28

2023-04-27 10:47 UTC, Nouzan commented
https://github.com/Nouzan/indicator/pull/28 has been merged and published with `v0.4.0-beta.0`. You can rebase and try again.

2023-04-28 02:06 UTC, rise0chen commented
ok

2023-04-28 04:07 UTC, Nouzan requested changes
Thank you for the improvements. Once the style issues are resolved, I will be happy to accept this PR.

2023-04-28 04:07 UTC, Nouzan commented on exc-okx/src/utils/period.rs
> +        let out_bar = period_to_bar(&period).unwrap_or_else(|| panic!("{} - {}", bar, period));
Maybe better use `.expect(&format!("{bar}"));`.

2023-04-28 04:07 UTC, Nouzan commented on exc-okx/src/utils/period.rs
> +        let out_period = bar_to_period(bar).unwrap_or_else(|| panic!("{} - {}", period, bar));
Same as above.

2023-04-28 05:07 UTC, rise0chen commented
It is suggested by [clippy](https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call)

2023-04-28 06:46 UTC, Nouzan commented
> It is suggested by [clippy](https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call)

Oh, I see.

2023-04-28 06:47 UTC, merged